package com.sba.cbr.entity;
// Generated Aug 14, 2025, 1:05:46 PM by Hibernate Tools 6.2.25.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "cbr")
@AttributeOverride(name = "id", column = @Column(name = "category_id"))
@AttributeOverride(name = "active", column = @Column(name = "is_active"))
public class Category extends BaseEntity implements java.io.Serializable {

	private String name;
	@Embedded
	private AuditFields audit; 
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	private Set<Book> books = new HashSet<Book>(0);

	public Category() {
	}

	public Category(String name) {
		this.name = name;
	}

	public Category(String name, Set books) {
		this.name = name;
		this.books = books;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}
	
	public AuditFields getAuditFields() {
		return audit;
	}
	
	public void setAuditFields(AuditFields audit) {
		this.audit = audit;
	}

}
