package com.sba.cbr.entity;
// Generated Aug 14, 2025, 1:05:46 PM by Hibernate Tools 6.2.25.Final

import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "Customer", catalog = "cbr", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@AttributeOverride(name = "id", column = @Column(name = "customer_id"))
@AttributeOverride(name = "active", column = @Column(name = "is_active"))
public class Customer extends BaseEntity implements java.io.Serializable {

	@Column(name = "email", unique = true, nullable = false, length = 64)
	private String email;
	private String firstname;
	private String lastname;
	private String address_line1;
	private String address_line2;
	private String city;
	private String country;
	private String phone;
	private String zipcode;
	private String password;
	
	@Embedded
	private AuditFields audit;
	@NotNull
	@Column(name = "is_active")
	private boolean active;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	private Set<Review> reviews = new HashSet<Review>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	private Set<BookOrder> bookOrders = new HashSet<BookOrder>(0);

	public Customer() {
	}

	public Customer(String email, String firstname, String lastname, String address_line1, String address_line2, String city, String country, String phone,
			String zipcode, String password, AuditFields audit) {
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.address_line1 = address_line1;
		this.address_line2 = address_line2;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
		this.audit = audit;
	}

	public Customer(String email, String firstname, String lastname, String address_line1, String address_line2, String city, String country, String phone,
			String zipcode, String password, AuditFields audit, Set reviews, Set bookOrders) {
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.address_line1 = address_line1;
		this.address_line2 = address_line2;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
		this.audit = audit;
		
		
		this.reviews = reviews;
		this.bookOrders = bookOrders;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	
	@Transient
	public String getFullname() {
		return this.firstname + " " + this.lastname;
	}


	public String getAddressLine1() {
		return this.address_line1;
	}

	public void setAddressLine1(String addressLine1) {
		this.address_line1 = addressLine1;
	}
	
	public String getAddressLine2() {
		return this.address_line2;
	}

	public void setAddressLine2(String addressLine2) {
		this.address_line2 = addressLine2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	
	@Transient
	public String getCountryName() {
		return new Locale("", this.country).getDisplayCountry();
	}


	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	public Set<BookOrder> getBookOrders() {
		return this.bookOrders;
	}

	public void setBookOrders(Set<BookOrder> bookOrders) {
		this.bookOrders = bookOrders;
	}
	
	public AuditFields getAuditFields() {
		return audit;
	}
	
	public void setAuditFields(AuditFields audit) {
		this.audit = audit;
	}

}
