package com.sba.cbr.entity2;
// Generated Aug 14, 2025, 1:05:46 PM by Hibernate Tools 6.2.25.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.sba.cbr.entity.AuditFields;
import com.sba.cbr.entity.BaseEntity;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "Customer", catalog = "cbr", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@AttributeOverride(name = "id", column = @Column(name = "customer_id"))
@AttributeOverride(name = "active", column = @Column(name = "is_active"))
public class Customer extends BaseEntity implements java.io.Serializable {

	@Column(name = "email", unique = true, nullable = false, length = 64)
	private String email;
	private String fullname;
	private String address;
	private String city;
	private String country;
	private String phone;
	private String zipcode;
	private String password;
	
	@Embedded
	private AuditFields audit;
	
	private Set reviews = new HashSet(0);
	private Set bookOrders = new HashSet(0);

	public Customer() {
	}

	public Customer(String email, String fullname, String address, String city, String country, String phone,
			String zipcode, String password) {
		this.email = email;
		this.fullname = fullname;
		this.address = address;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
	}

	public Customer(String email, String fullname, String address, String city, String country, String phone,
			String zipcode, String password, Set reviews, Set bookOrders) {
		this.email = email;
		this.fullname = fullname;
		this.address = address;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
		this.reviews = reviews;
		this.bookOrders = bookOrders;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

	public Set getBookOrders() {
		return this.bookOrders;
	}

	public void setBookOrders(Set bookOrders) {
		this.bookOrders = bookOrders;
	}

}
