package com.sba.cbr.entity2;
// Generated Aug 14, 2025, 1:05:46 PM by Hibernate Tools 6.2.25.Final

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private OrderDetailId id;
	private BookOrder bookOrder;
	private Book book;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId id) {
		this.id = id;
	}

	public OrderDetail(OrderDetailId id, BookOrder bookOrder, Book book) {
		this.id = id;
		this.bookOrder = bookOrder;
		this.book = book;
	}

	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	public BookOrder getBookOrder() {
		return this.bookOrder;
	}

	public void setBookOrder(BookOrder bookOrder) {
		this.bookOrder = bookOrder;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

}
