package com.sba.cbr.entity2;
// Generated Aug 14, 2025, 1:05:46 PM by Hibernate Tools 6.2.25.Final

import java.sql.Timestamp;

/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId implements java.io.Serializable {

	private Integer bookId;
	private Timestamp createdAt;
	private int createdBy;
	private boolean isActive;
	private Integer orderId;
	private int quantity;
	private float subtotal;
	private Timestamp updatedAt;
	private int updatedBy;

	public OrderDetailId() {
	}

	public OrderDetailId(Timestamp createdAt, int createdBy, boolean isActive, int quantity, float subtotal,
			Timestamp updatedAt, int updatedBy) {
		this.createdAt = createdAt;
		this.createdBy = createdBy;
		this.isActive = isActive;
		this.quantity = quantity;
		this.subtotal = subtotal;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public OrderDetailId(Integer bookId, Timestamp createdAt, int createdBy, boolean isActive, Integer orderId,
			int quantity, float subtotal, Timestamp updatedAt, int updatedBy) {
		this.bookId = bookId;
		this.createdAt = createdAt;
		this.createdBy = createdBy;
		this.isActive = isActive;
		this.orderId = orderId;
		this.quantity = quantity;
		this.subtotal = subtotal;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;

		return ((this.getBookId() == castOther.getBookId()) || (this.getBookId() != null
				&& castOther.getBookId() != null && this.getBookId().equals(castOther.getBookId())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& (this.getCreatedBy() == castOther.getCreatedBy()) && (this.isIsActive() == castOther.isIsActive())
				&& ((this.getOrderId() == castOther.getOrderId()) || (this.getOrderId() != null
						&& castOther.getOrderId() != null && this.getOrderId().equals(castOther.getOrderId())))
				&& (this.getQuantity() == castOther.getQuantity()) && (this.getSubtotal() == castOther.getSubtotal())
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& (this.getUpdatedBy() == castOther.getUpdatedBy());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBookId() == null ? 0 : this.getBookId().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + this.getCreatedBy();
		result = 37 * result + (this.isIsActive() ? 1 : 0);
		result = 37 * result + (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37 * result + this.getQuantity();
		result = 37 * result + (int) this.getSubtotal();
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + this.getUpdatedBy();
		return result;
	}

}
