package com.sba.cbr.entity2;
// Generated Aug 14, 2025, 1:05:46 PM by Hibernate Tools 6.2.25.Final

import java.sql.Timestamp;

import com.sba.cbr.entity.AuditFields;
import com.sba.cbr.entity.BaseEntity;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name="review")
@AttributeOverride(name="id", column= @Column(name="review_id"))
@AttributeOverride(name = "active", column = @Column(name = "is_active"))
public class Review extends BaseEntity implements java.io.Serializable {

	
	private Customer customer;
	private Book book;
	private int rating;
	private String headline;
	private String comment;
	private AuditFields audit;

	public Review() {
	}

	public Review(Customer customer, Book book, int rating, String headline, String comment, AuditFields audit) {
		this.customer = customer;
		this.book = book;
		this.rating = rating;
		this.headline = headline;
		this.comment = comment;
	}


	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
